/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DudenNFT } from "./DudenNFT";
export type { DudenNFTFactory } from "./DudenNFTFactory";
export type { Web3BridgeGarage } from "./Web3BridgeGarage";
